# Generated by Django 5.2.7 on 2026-04-29 15:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0004_alter_program_options_program_short_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=120, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('cecc_chairman_rate', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('cecc_member_rate', models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10)),
                ('ec_chairman_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ec_member_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qmsc_chairman_rate', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10)),
                ('qmsc_member_rate', models.DecimalField(decimal_places=2, default=Decimal('200.00'), max_digits=10)),
                ('rpsc_chairman_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=10)),
                ('rpsc_member_rate', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=10)),
                ('qpsc_member_rate', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('qsetter_full_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('400.00'), max_digits=10)),
                ('qsetter_full_non_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10)),
                ('qsetter_half_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('250.00'), max_digits=10)),
                ('qsetter_half_non_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
                ('examiner_full_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10)),
                ('examiner_full_non_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10)),
                ('examiner_half_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10)),
                ('examiner_half_non_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=10)),
                ('scrutinizer_full_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('scrutinizer_full_non_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('scrutinizer_half_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=10)),
                ('scrutinizer_half_non_engineering_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=10)),
                ('qmsc_question_mode', models.CharField(choices=[('UNIQUE', 'Unique Questions'), ('DUPLICATE', 'Duplicate Questions')], default='UNIQUE', max_length=20)),
                ('qpsc_question_mode', models.CharField(choices=[('UNIQUE', 'Unique Questions'), ('DUPLICATE', 'Duplicate Questions')], default='DUPLICATE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillingExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(default='FINAL', max_length=50)),
                ('semester_label', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('locked', 'Locked'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'exam_type', 'semester_label')},
            },
        ),
        migrations.CreateModel(
            name='ExamBillingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cecc_chairman_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cecc_member_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ec_chairman_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ec_member_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qmsc_chairman_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qmsc_member_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rpsc_chairman_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rpsc_member_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qpsc_member_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qsetter_full_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qsetter_full_non_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qsetter_half_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qsetter_half_non_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examiner_full_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examiner_full_non_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examiner_half_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('examiner_half_non_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scrutinizer_full_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scrutinizer_full_non_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scrutinizer_half_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scrutinizer_half_non_engineering_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qmsc_question_mode', models.CharField(choices=[('UNIQUE', 'Unique Questions'), ('DUPLICATE', 'Duplicate Questions')], max_length=20)),
                ('qpsc_question_mode', models.CharField(choices=[('UNIQUE', 'Unique Questions'), ('DUPLICATE', 'Duplicate Questions')], max_length=20)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='exam_billing.billingexam')),
                ('source_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_billing.billingratetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ExamProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='exam_billing.billingexam')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_exams', to='master_data.program')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exam', 'program__sort_order', 'program__name'],
                'unique_together': {('exam', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ExamCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
                ('term', models.CharField(max_length=30)),
                ('course_code', models.CharField(max_length=50)),
                ('offering_department', models.CharField(blank=True, max_length=100)),
                ('no_of_scripts', models.PositiveIntegerField(default=0)),
                ('syllabus', models.CharField(blank=True, max_length=100)),
                ('course_title', models.CharField(blank=True, max_length=255)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('is_engineering', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='exam_billing.examprogram')),
            ],
            options={
                'ordering': ['level', 'term', 'course_code'],
                'unique_together': {('exam_program', 'course_code')},
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_profiles', to='master_data.program')),
            ],
            options={
                'ordering': ['program__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_snapshot', models.CharField(blank=True, max_length=120)),
                ('is_deleted', models.BooleanField(default=False)),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_entries', to='exam_billing.facultyprofile')),
            ],
            options={
                'ordering': ['faculty__name'],
            },
        ),
        migrations.CreateModel(
            name='ECMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(blank=True, max_length=30)),
                ('term', models.CharField(blank=True, max_length=30)),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec_members', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CECCAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cecc_assignments', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QMSCAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_external', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qmsc_assignments', to='exam_billing.examcourse')),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qmsc_assignments', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QPSCMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qpsc_members', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionSetterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('A+B', 'A+B')], default='A', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='question_setters', to='exam_billing.examcourse')),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_setters', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RPSCAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=30)),
                ('term', models.CharField(max_length=30)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpsc_assignments', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptExaminerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('A+B', 'A+B')], default='A', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='script_examiners', to='exam_billing.examcourse')),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_examiners', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptScrutinizerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('A+B', 'A+B')], default='A', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='script_scrutinizers', to='exam_billing.examcourse')),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_scrutinizers', to='exam_billing.examprogram')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='facultyprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id', ''), _negated=True), fields=('program', 'employee_id'), name='unique_billing_faculty_employee_per_program'),
        ),
        migrations.AlterUniqueTogether(
            name='examfaculty',
            unique_together={('exam_program', 'faculty')},
        ),
    ]
