# Generated by Django 5.2.7 on 2026-04-29 22:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprogram',
            name='cached_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examprogram',
            name='cached_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='examprogram',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
