# Generated by Django 5.2.7 on 2026-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0002_examprogram_cached_summary_examprogram_cached_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
