# Generated by Django 5.2.7 on 2026-04-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0004_facultyprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='first_name',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='last_name',
            field=models.CharField(default='', max_length=75),
        ),
    ]
