# Generated by Django 5.2.7 on 2026-04-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0005_facultyprofile_first_name_facultyprofile_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examfaculty',
            options={'ordering': ['faculty__first_name', 'faculty__last_name']},
        ),
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'ordering': ['program__name', 'first_name', 'last_name']},
        ),
        migrations.RenameField(
            model_name='billingratetemplate',
            old_name='qmsc_question_mode',
            new_name='rpsc_question_mode',
        ),
        migrations.RenameField(
            model_name='exambillingsetting',
            old_name='qmsc_question_mode',
            new_name='rpsc_question_mode',
        ),
        migrations.RemoveField(
            model_name='facultyprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='first_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
