# Generated by Django 5.2.7 on 2026-04-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0006_alter_examfaculty_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLevelTermSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
                ('term', models.CharField(max_length=30)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('exam_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_term_summaries', to='exam_billing.examprogram')),
            ],
            options={
                'ordering': ['level', 'term'],
                'unique_together': {('exam_program', 'level', 'term')},
            },
        ),
    ]
