# Generated by Django 5.2.7 on 2026-04-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0007_examleveltermsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcourse',
            name='is_engineering',
        ),
        migrations.RemoveField(
            model_name='examcourse',
            name='total_students',
        ),
    ]
