# Generated by Django 5.2.7 on 2026-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0008_remove_examcourse_is_engineering_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examcourse',
            unique_together={('exam_program', 'course_code', 'syllabus')},
        ),
        migrations.AlterField(
            model_name='examcourse',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')], max_length=30),
        ),
        migrations.AlterField(
            model_name='examcourse',
            name='term',
            field=models.CharField(choices=[('I', 'Term I'), ('II', 'Term II')], max_length=30),
        ),
        migrations.AlterField(
            model_name='examleveltermsummary',
            name='level',
            field=models.CharField(choices=[('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')], max_length=30),
        ),
        migrations.AlterField(
            model_name='examleveltermsummary',
            name='term',
            field=models.CharField(choices=[('I', 'Term I'), ('II', 'Term II')], max_length=30),
        ),
    ]
