# Generated by Django 5.2.7 on 2026-05-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0009_alter_examcourse_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpscassignment',
            name='total_students',
        ),
        migrations.AlterField(
            model_name='examprogram',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('locked', 'Locked'), ('finalized', 'Finalized')], default='draft', max_length=20),
        ),
    ]
