# Generated by Django 5.2.7 on 2026-05-01 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0010_remove_rpsc_total_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecmember',
            name='level',
        ),
        migrations.RemoveField(
            model_name='ecmember',
            name='term',
        ),
        migrations.RemoveField(
            model_name='qmscassignment',
            name='is_external',
        ),
        migrations.AddField(
            model_name='qmscassignment',
            name='external_member_designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='qmscassignment',
            name='external_member_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='qmscassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qmsc_assignments', to='exam_billing.examcourse'),
        ),
        migrations.AlterField(
            model_name='qmscassignment',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exam_billing.facultyprofile'),
        ),
        migrations.AlterField(
            model_name='rpscassignment',
            name='level',
            field=models.CharField(choices=[('All', 'All'), ('1', 'Level 1'), ('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')], default='All', max_length=10),
        ),
        migrations.AlterField(
            model_name='rpscassignment',
            name='term',
            field=models.CharField(choices=[('All', 'All'), ('I', 'Term I'), ('II', 'Term II')], default='All', max_length=10),
        ),
    ]
