# Generated by Django 6.0.3 on 2026-05-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_billing', '0011_redesign_committees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qmscassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qmsc_assignments', to='exam_billing.examcourse'),
        ),
        migrations.AddConstraint(
            model_name='qmscassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('role', 'Member')), fields=('exam_program', 'course'), name='unique_active_qmsc_member_per_course'),
        ),
        migrations.AddConstraint(
            model_name='qmscassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('role', 'Chairman')), fields=('exam_program',), name='unique_active_qmsc_chairman_per_program'),
        ),
        migrations.AddConstraint(
            model_name='questionsetterassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('exam_program', 'course', 'part'), name='unique_active_qsetter_per_course_part'),
        ),
        migrations.AddConstraint(
            model_name='rpscassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('exam_program', 'level', 'term', 'role'), name='unique_rpsc_assignment_role_per_slot'),
        ),
        migrations.AddConstraint(
            model_name='scriptexaminerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('exam_program', 'course', 'part'), name='unique_active_examiner_per_course_part'),
        ),
        migrations.AddConstraint(
            model_name='scriptscrutinizerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('exam_program', 'course', 'part'), name='unique_active_scrutinizer_per_course_part'),
        ),
    ]
