# Generated by Django 5.2.7 on 2026-07-22 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0010_hall_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id_prefix', models.CharField(default='APP', max_length=10, verbose_name='Tracking ID Prefix')),
                ('sms_notify_submit', models.BooleanField(default=True, verbose_name='SMS on Submission')),
                ('sms_notify_approved', models.BooleanField(default=True, verbose_name='SMS on HoD Approval')),
                ('sms_notify_ready', models.BooleanField(default=True, verbose_name='SMS When Ready for Delivery')),
                ('sms_delivery_otp', models.BooleanField(default=True, verbose_name='SMS Delivery OTP')),
                ('attachment_max_mb', models.IntegerField(default=2, verbose_name='Max Attachment Size (MB)')),
                ('rejected_purge_days', models.IntegerField(default=15, verbose_name='Rejected File Purge (days)')),
                ('delivered_purge_days', models.IntegerField(default=90, verbose_name='Delivered File Purge (days)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'CoE Settings',
                'verbose_name_plural': 'CoE Settings',
            },
        ),
        migrations.CreateModel(
            name='DocumentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Application Number')),
                ('tracking_pin', models.CharField(editable=False, max_length=4, verbose_name='Tracking PIN')),
                ('application_type', models.CharField(choices=[('main_certificate', 'Main/Original Certificate'), ('provisional_transcript', 'Provisional / Main Academic Transcript'), ('incomplete_transcript', 'Incomplete Academic Transcript'), ('name_correction', "Student's Name Correction"), ('parent_name_correction', 'Father/Mother Name Correction'), ('recommendation_letter', 'Recommendation Letter'), ('grade_sheet', 'Grade Sheet'), ('duplicate_document', 'Duplicate Documents (as per GD)')], max_length=30, verbose_name='Application Type')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_hod_review', 'Under HoD Review'), ('pending_coe_assignment', 'Pending CoE Assignment'), ('in_processing', 'In Processing'), ('action_required', 'Action Required by Student'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=30, verbose_name='Status')),
                ('student_name', models.CharField(max_length=200, verbose_name='Student Name')),
                ('student_id', models.CharField(max_length=30, verbose_name='Student ID')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('session', models.CharField(max_length=20, verbose_name='Session')),
                ('admission_batch', models.CharField(max_length=10, verbose_name='Admission Batch')),
                ('father_name', models.CharField(blank=True, max_length=200, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=200, verbose_name="Mother's Name")),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('passing_semester', models.CharField(max_length=30, verbose_name='Passing Semester')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='CGPA')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='Result Publication Date')),
                ('corrected_name', models.CharField(blank=True, max_length=200, verbose_name='Corrected Student Name')),
                ('corrected_parent_name', models.CharField(blank=True, max_length=200, verbose_name='Corrected Parent Name')),
                ('purpose_destination', models.TextField(blank=True, verbose_name='Purpose / Destination')),
                ('level_term', models.CharField(blank=True, max_length=30, verbose_name='Level / Term')),
                ('missing_doc_type', models.CharField(blank=True, max_length=100, verbose_name='Missing Document Type')),
                ('dept_head_note', models.TextField(blank=True, verbose_name='Dept. Head Note')),
                ('processing_note', models.TextField(blank=True, verbose_name='Processing Note')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('delivery_otp', models.CharField(blank=True, max_length=6, verbose_name='Delivery OTP')),
                ('delivery_otp_verified', models.BooleanField(default=False, verbose_name='OTP Verified')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Soft Deleted')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coe_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To (Processing Officer)')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coe_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Delivered By')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coe_applications', to='master_data.program', verbose_name='Department / Program')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coe_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Document Application',
                'verbose_name_plural': 'Document Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30, verbose_name='Previous Status')),
                ('new_status', models.CharField(max_length=30, verbose_name='New Status')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS Sent')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Changed At')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coe_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='coe.documentapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Status Log Entry',
                'verbose_name_plural': 'Status Log Entries',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('final_clearance', 'Final Clearance'), ('payment_slip', 'Payment Slip'), ('ssc_cert', 'SSC Certificate'), ('hsc_cert', 'HSC Certificate'), ('nid_photocopy', 'NID Photocopy'), ('offer_letter', 'Offer Letter (Printed Copy)'), ('baust_mce', 'BAUST — Migration Certificate (MCE)'), ('baust_moi', 'BAUST — Migration of Institution (MoI)'), ('baust_mc', 'BAUST — Mark Certificate (MC)'), ('baust_ts', 'BAUST — Testimonial Sheet (TS)'), ('gd_copy', 'General Diary (GD) Copy'), ('missing_doc_copy', 'Missing Document Copy'), ('other', 'Other Document')], max_length=30, verbose_name='Attachment Type')),
                ('file', models.FileField(upload_to='coe/attachments/', verbose_name='File')),
                ('sha256_hash', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 Hash')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original Filename')),
                ('file_size_kb', models.IntegerField(default=0, verbose_name='File Size (KB)')),
                ('is_purged', models.BooleanField(default=False, verbose_name='File Purged')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='coe.documentapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Application Attachment',
                'verbose_name_plural': 'Application Attachments',
                'ordering': ['attachment_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_api_fetched', models.BooleanField(default=False, verbose_name='Admission API Fetched')),
                ('admission_api_data', models.JSONField(blank=True, null=True, verbose_name='Admission API Data')),
                ('board_api_fetched', models.BooleanField(default=False, verbose_name='Board API Fetched')),
                ('board_api_data', models.JSONField(blank=True, null=True, verbose_name='Board API Data')),
                ('board_roll', models.CharField(blank=True, max_length=30, verbose_name='Board Roll')),
                ('board_registration', models.CharField(blank=True, max_length=30, verbose_name='Board Registration')),
                ('board_name', models.CharField(blank=True, max_length=100, verbose_name='Board Name')),
                ('board_year', models.CharField(blank=True, max_length=10, verbose_name='Board Year')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='coe.documentapplication', verbose_name='Application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coe_verifications', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Processing Verification',
                'verbose_name_plural': 'Processing Verifications',
            },
        ),
        migrations.AddIndex(
            model_name='documentapplication',
            index=models.Index(fields=['status', 'submitted_at'], name='coe_documen_status_19c483_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapplication',
            index=models.Index(fields=['student_id'], name='coe_documen_student_3481e3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapplication',
            index=models.Index(fields=['application_number'], name='coe_documen_applica_f3da0f_idx'),
        ),
    ]
