# Generated by Django 5.2.7 on 2026-07-23 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coesettings',
            name='enable_auto_assignment',
            field=models.BooleanField(default=False, verbose_name='Enable Auto Assignment'),
        ),
        migrations.CreateModel(
            name='CoeAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('main_certificate', 'Main/Original Certificate'), ('provisional_transcript', 'Provisional / Main Academic Transcript'), ('incomplete_transcript', 'Incomplete Academic Transcript'), ('name_correction', "Student's Name Correction"), ('parent_name_correction', 'Father/Mother Name Correction'), ('recommendation_letter', 'Recommendation Letter'), ('grade_sheet', 'Grade Sheet'), ('duplicate_document', 'Duplicate Documents (as per GD)')], max_length=50, unique=True, verbose_name='Application Type')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coe_assignment_rules', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Officer')),
            ],
            options={
                'verbose_name': 'CoE Assignment Rule',
                'verbose_name_plural': 'CoE Assignment Rules',
            },
        ),
    ]
