# Generated by Django 6.0.3 on 2026-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0002_coesettings_enable_auto_assignment_coeassignmentrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentapplication',
            name='student_id',
            field=models.CharField(max_length=16, verbose_name='Student ID'),
        ),
    ]
