# Generated by Django 6.0.3 on 2026-04-20 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_student_id', models.CharField(max_length=50)),
                ('new_student_id', models.CharField(max_length=50)),
                ('old_program', models.CharField(max_length=100)),
                ('new_program', models.CharField(max_length=100)),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Program change histories',
            },
        ),
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient_contact', models.CharField(max_length=50)),
                ('sms_delivery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('message_type', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('api_response', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('api_profile_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'SMS Histories',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(help_text='UGC Compliant ID', max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('old_student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_year', models.IntegerField(blank=True, null=True)),
                ('cluster', models.CharField(blank=True, max_length=50, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('semester_name', models.CharField(blank=True, max_length=50, null=True)),
                ('program_type', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_status', models.CharField(default='Active', max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('student_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('father_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('ssc_school', models.CharField(blank=True, max_length=255, null=True)),
                ('ssc_year', models.CharField(blank=True, max_length=10, null=True)),
                ('ssc_board', models.CharField(blank=True, max_length=50, null=True)),
                ('ssc_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('ssc_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('ssc_gpa', models.FloatField(blank=True, null=True)),
                ('hsc_college', models.CharField(blank=True, max_length=255, null=True)),
                ('hsc_year', models.CharField(blank=True, max_length=10, null=True)),
                ('hsc_board', models.CharField(blank=True, max_length=50, null=True)),
                ('hsc_roll', models.CharField(blank=True, max_length=50, null=True)),
                ('hsc_reg', models.CharField(blank=True, max_length=50, null=True)),
                ('hsc_gpa', models.FloatField(blank=True, null=True)),
                ('hall_attached', models.CharField(blank=True, max_length=100, null=True)),
                ('is_non_residential', models.BooleanField(default=False)),
                ('admission_payment', models.FloatField(default=0.0)),
                ('second_installment', models.FloatField(default=0.0)),
                ('waiver', models.FloatField(default=0.0)),
                ('others', models.FloatField(default=0.0)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_temp_admission_cancel', models.BooleanField(default=False)),
                ('is_credit_transfer', models.BooleanField(default=False)),
                ('is_armed_forces_child', models.BooleanField(default=False)),
                ('is_freedom_fighter_child', models.BooleanField(default=False)),
                ('is_july_joddha_2024', models.BooleanField(default=False)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('mba_credits', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
