# Generated by Django 5.2.7 on 2026-04-21 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_admission_payment_alter_student_others_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smshistory',
            options={},
        ),
        migrations.CreateModel(
            name='AdmissionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('reason_category', models.CharField(choices=[('Migration', 'Migration to other University'), ('Financial', 'Financial/Non-Payment'), ('Personal', 'Personal Reasons'), ('Academic', 'Academic Non-Performance'), ('Disciplinary', 'Disciplinary Action'), ('Other', 'Other (See Notes)')], max_length=50)),
                ('custom_notes', models.TextField(blank=True, null=True)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Admission status histories',
                'ordering': ['-change_date'],
            },
        ),
    ]
