# Generated by Django 5.2.7 on 2026-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_smshistory_options_admissionstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_number',
            field=models.IntegerField(blank=True, help_text='Auto-extracted for numeric sorting', null=True),
        ),
    ]
