# Generated by Django 6.0.3 on 2026-04-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_backfill_student_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_upazila',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_upazila',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
