# Generated by Django 6.0.3 on 2026-04-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_permanent_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hsc_chemistry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_math',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_physics',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_chemistry',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_math',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_physics',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
