# Generated by Django 5.2.7 on 2026-05-14 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_hsc_chemistry_student_hsc_math_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_verification_logs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_status',
            field=models.CharField(db_index=True, default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_mobile',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
