# Generated by Django 6.0.3 on 2026-06-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentfieldhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_legacy_student',
            field=models.BooleanField(default=False, help_text='True for pre-digital-era students (Batch 1–12) added retrospectively with their original 9-digit ID.'),
        ),
    ]
