# Generated by Django 6.0.3 on 2026-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_add_is_legacy_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_batch',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
