# Generated by Django 6.0.3 on 2026-06-17

from django.db import migrations
import re

def rectify_legacy_students(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Student = apps.get_model('students', 'Student')
    for s in Student.objects.using(db_alias).all():
        s_id = str(s.student_id).strip()
        is_legacy = False
        
        # Less than 16 digit ID
        if len(s_id) < 16:
            is_legacy = True
            
        # Batch 1 to 12
        if s.batch:
            nums = re.findall(r'\d+', str(s.batch))
            if nums:
                batch_num = int(nums[0])
                if 1 <= batch_num <= 12:
                    is_legacy = True
                    
        if is_legacy and not s.is_legacy_student:
            s.is_legacy_student = True
            s.save(using=db_alias)

def reverse_rectify(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_current_batch_student_current_semester'),
    ]

    operations = [
        migrations.RunPython(rectify_legacy_students, reverse_code=reverse_rectify),
    ]
