# Generated by Django 6.0.3 on 2026-06-25 08:13

import django.db.models.deletion
from django.db import migrations, models

def copy_to_legacy(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Student = apps.get_model('students', 'Student')
    for s in Student.objects.using(db_alias).all():
        s.reference_legacy = s.reference
        # Always set to None (NULL) to clean the column for the ForeignKey AlterField operation
        s.reference = None
        s.save(using=db_alias)

def populate_foreign_keys(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Student = apps.get_model('students', 'Student')
    ReferenceNode = apps.get_model('students', 'ReferenceNode')
    
    # Map to store created nodes
    node_map = {}
    
    # Query Student objects where reference_legacy is not null/empty
    students_with_legacy = Student.objects.using(db_alias).exclude(reference_legacy__isnull=True).exclude(reference_legacy='')
    
    next_id = 1
    for s in students_with_legacy:
        legacy_str = s.reference_legacy.strip()
        if not legacy_str:
            continue
            
        if legacy_str not in node_map:
            # Manually generate reference_id since historical models in migrations bypass custom save()
            ref_id = f"REF-{next_id:05d}"
            while ReferenceNode.objects.using(db_alias).filter(reference_id=ref_id).exists():
                next_id += 1
                ref_id = f"REF-{next_id:05d}"
                
            node = ReferenceNode.objects.using(db_alias).create(
                name_en=legacy_str,
                reference_id=ref_id
            )
            node_map[legacy_str] = node
            next_id += 1
            
        s.reference = node_map[legacy_str]
        s.save(using=db_alias)

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_rectify_legacy_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('baust_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='reference_legacy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(copy_to_legacy, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.referencenode'),
        ),
        migrations.RunPython(populate_foreign_keys, reverse_code=migrations.RunPython.noop),
    ]
