# Generated by Django 6.0.3 on 2026-06-28 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_referencenode_student_reference_legacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='referred_by_student',
            field=models.ForeignKey(blank=True, help_text='Referrer if they are an existing student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_students', to='students.student'),
        ),
    ]
