# Generated by Django 6.0.3 on 2026-06-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_referred_by_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencenode',
            name='category',
            field=models.CharField(choices=[('Employee', 'Employee'), ('External', 'External')], default='Employee', max_length=20),
        ),
    ]
