# Generated by Django 6.0.3 on 2026-06-28

from django.db import migrations

def convert_to_utf8(apps, schema_editor):
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Disable FK checks to safely alter table collation
            cursor.execute("SET FOREIGN_KEY_CHECKS=0;")
            
            # Convert students_referencenode table and all its string fields to utf8mb4
            cursor.execute("ALTER TABLE students_referencenode CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
            
            cursor.execute("SET FOREIGN_KEY_CHECKS=1;")

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_referencenode_category'),
    ]

    operations = [
        migrations.RunPython(convert_to_utf8, reverse_code=migrations.RunPython.noop),
    ]
