# Generated by Django 6.0.3 on 2026-06-28

from django.db import migrations, models

def mark_unverified_legacy_nodes(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ReferenceNode = apps.get_model('students', 'ReferenceNode')
    # Mark all reference nodes created from legacy raw text (no additional info) as unverified
    ReferenceNode.objects.using(db_alias).filter(
        models.Q(designation__isnull=True) | models.Q(designation=''),
        models.Q(mobile__isnull=True) | models.Q(mobile=''),
        models.Q(baust_id__isnull=True) | models.Q(baust_id=''),
        models.Q(name_bn__isnull=True) | models.Q(name_bn='')
    ).update(is_verified=False)

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_referencenode_utf8'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencenode',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(mark_unverified_legacy_nodes, reverse_code=migrations.RunPython.noop),
    ]
