# Generated by Django 6.0.3 on 2026-07-07 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_residential_halls(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Hall = apps.get_model('master_data', 'Hall')
    from django.db.models import Q
    
    # Pre-fetch all halls and create a map from short_name/full_name to Hall instance
    hall_map = {}
    for h in Hall.objects.all():
        if h.short_name:
            hall_map[h.short_name.lower().strip()] = h
        if h.full_name:
            hall_map[h.full_name.lower().strip()] = h

    for student in Student.objects.iterator():
        if student.is_non_residential:
            student.hall_residential = None
        elif student.hall_attached:
            key = student.hall_attached.lower().strip()
            hall_obj = hall_map.get(key)
            if hall_obj:
                student.hall_residential = hall_obj
            else:
                found_hall = Hall.objects.filter(
                    Q(short_name__icontains=student.hall_attached) | Q(full_name__icontains=student.hall_attached)
                ).first()
                if found_hall:
                    student.hall_residential = found_hall
        
        student.save(update_fields=['hall_residential'])


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_set_english_short_name'),
        ('students', '0018_referencenode_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hall_residential',
            field=models.ForeignKey(blank=True, help_text='The actual hall where the student physically resides.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='master_data.hall'),
        ),
        migrations.CreateModel(
            name='HallMigrationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration_date', models.DateTimeField(auto_now_add=True)),
                ('previous_residency_status', models.BooleanField(default=False, help_text='True if was non-residential previously')),
                ('new_residency_status', models.BooleanField(default=False, help_text='True if is non-residential now')),
                ('reason', models.TextField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('new_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrations_in', to='master_data.hall')),
                ('previous_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrations_out', to='master_data.hall')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_history', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Hall migration histories',
                'ordering': ['-migration_date'],
            },
        ),
        migrations.RunPython(backfill_residential_halls, reverse_code=migrations.RunPython.noop),
    ]
