# Generated by Django 6.0.3 on 2026-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_student_hall_residential_hallmigrationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bteb_curriculum',
            field=models.CharField(blank=True, help_text="BTEB Curriculum code+name, e.g. '27 - SSC (Vocational)' or '10 - Diploma in Engineering'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bteb_semester',
            field=models.CharField(blank=True, help_text="BTEB Semester/Class number, e.g. '1', '4', '8'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bteb_verified',
            field=models.BooleanField(default=False),
        ),
    ]
