# Generated by Django 5.2.7 on 2026-07-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_add_bteb_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfieldhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfieldhistory',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
