# Generated by Django 5.2.7 on 2026-07-14 17:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_hall_capacity'),
        ('students', '0021_studentfieldhistory_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HallSeatCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('GRADUATION', 'Completed Graduation / Completed Program'), ('VOLUNTARY', 'Voluntary Release (Commuting / Private Mess)'), ('DISCIPLINARY', 'Disciplinary Action'), ('TRANSFER', 'Transfer to Another Campus / Institution'), ('NON_PAYMENT', 'Non-payment of Hall Dues'), ('OTHER', 'Other (Please specify in notes)')], default='VOLUNTARY', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Additional explanation or context', null=True)),
                ('refund_applicable', models.BooleanField(default=False, help_text='Check if student is eligible for caution money/fee refund')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.admissionyear')),
                ('authorized_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='master_data.hall')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_cancellations', to='students.student')),
            ],
            options={
                'verbose_name': 'Hall Seat Cancellation',
                'verbose_name_plural': 'Hall Seat Cancellations',
                'ordering': ['-cancellation_date'],
            },
        ),
    ]
