# Generated by Django 5.2.7 on 2026-07-15 13:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='পত্রিকা বা পোর্টালের সম্পূর্ণ নাম', max_length=255, unique=True, verbose_name='মিডিয়ার নাম')),
                ('media_type', models.CharField(choices=[('national', 'জাতীয় পত্রিকা (National)'), ('local', 'স্থানীয় পত্রিকা (Local)'), ('online', 'অনলাইন পোর্টাল (Online)')], max_length=10, verbose_name='মিডিয়া ধরন')),
                ('editor', models.CharField(blank=True, help_text='প্রধান সম্পাদকের নাম', max_length=255, verbose_name='সম্পাদক')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('mobile', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='বৈধ বাংলাদেশি মোবাইল নম্বর দিন (যেমন: 01712345678)', regex='^(?:\\+?88)?01[3-9]\\d{8}$')], verbose_name='মোবাইল')),
                ('website', models.URLField(blank=True, verbose_name='ওয়েবসাইট')),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='বৈধ বাংলাদেশি মোবাইল নম্বর দিন (যেমন: 01712345678)', regex='^(?:\\+?88)?01[3-9]\\d{8}$')], verbose_name='হোয়াটসঅ্যাপ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'মিডিয়া হাউস',
                'verbose_name_plural': 'মিডিয়া হাউস তালিকা',
                'ordering': ['media_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PublicRelationsArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_release_no', models.CharField(help_text='অনন্য সিরিয়াল (যেমন: PRO-2024-001)', max_length=50, unique=True, verbose_name='প্রেস রিলিজ নং')),
                ('press_release_date', models.DateField(verbose_name='প্রেস রিলিজের তারিখ')),
                ('event_name', models.CharField(max_length=500, verbose_name='অনুষ্ঠানের নাম / শিরোনাম')),
                ('department', models.CharField(blank=True, help_text='সংশ্লিষ্ট বিভাগ বা অনুষদের নাম', max_length=150, verbose_name='বিভাগ / অনুষদ')),
                ('full_text', models.TextField(help_text='বাংলা বা ইংরেজিতে সম্পূর্ণ পাঠ্য', verbose_name='প্রেস রিলিজের পূর্ণ বিবরণ')),
                ('press_release_pdf', models.FileField(blank=True, null=True, upload_to='pr/press_releases/', verbose_name='প্রেস রিলিজ PDF')),
                ('remarks', models.TextField(blank=True, verbose_name='মন্তব্য / বিশেষ নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_archives', to=settings.AUTH_USER_MODEL, verbose_name='তৈরি করেছেন')),
            ],
            options={
                'verbose_name': 'প্রেস রিলিজ আর্কাইভ',
                'verbose_name_plural': 'প্রেস রিলিজ আর্কাইভ',
                'ordering': ['-press_release_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('photo', 'ছবি (Photo)'), ('video', 'ভিডিও (Video)'), ('drive', 'Google Drive'), ('youtube', 'YouTube'), ('facebook', 'Facebook')], max_length=10, verbose_name='অ্যাসেটের ধরন')),
                ('file', models.FileField(blank=True, null=True, upload_to='pr/assets/', verbose_name='ফাইল আপলোড (ছবি/ভিডিও)')),
                ('link', models.URLField(blank=True, verbose_name='বাহ্যিক লিংক (YouTube / Drive / Facebook)')),
                ('year', models.PositiveIntegerField(default=2026, help_text='অ্যাসেটটি যে বছরের (যেমন: 2024)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='সাল')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='ক্যাপশন / বিবরণ')),
                ('archive_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='public_relations.publicrelationsarchive', verbose_name='আর্কাইভ এন্ট্রি')),
            ],
            options={
                'verbose_name': 'মিডিয়া অ্যাসেট',
                'verbose_name_plural': 'মিডিয়া অ্যাসেট',
                'ordering': ['-year', 'asset_type'],
            },
        ),
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='প্রকাশের তারিখ')),
                ('newspaper_pdf', models.FileField(blank=True, null=True, upload_to='pr/coverage_pdfs/', verbose_name='পত্রিকার PDF কাটিং')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='pr/screenshots/', verbose_name='স্ক্রিনশট (অনলাইন কভারেজ)')),
                ('online_link', models.URLField(blank=True, verbose_name='অনলাইন নিউজ লিংক')),
                ('media_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='public_relations.mediahouse', verbose_name='মিডিয়া হাউস')),
                ('archive_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='public_relations.publicrelationsarchive', verbose_name='আর্কাইভ এন্ট্রি')),
            ],
            options={
                'verbose_name': 'মিডিয়া কভারেজ',
                'verbose_name_plural': 'মিডিয়া কভারেজ',
                'ordering': ['-published_date'],
                'unique_together': {('archive_entry', 'media_house')},
            },
        ),
    ]
