# Generated by Django 5.2.7 on 2026-07-15 16:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['-year', 'asset_type'], 'verbose_name': 'Media Asset', 'verbose_name_plural': 'Media Assets'},
        ),
        migrations.AlterModelOptions(
            name='mediacoverage',
            options={'ordering': ['-published_date'], 'verbose_name': 'Media Coverage', 'verbose_name_plural': 'Media Coverages'},
        ),
        migrations.AlterModelOptions(
            name='mediahouse',
            options={'ordering': ['media_type', 'name'], 'verbose_name': 'Media House', 'verbose_name_plural': 'Media Houses'},
        ),
        migrations.AlterModelOptions(
            name='publicrelationsarchive',
            options={'ordering': ['-press_release_date', '-created_at'], 'verbose_name': 'Press Release Archive', 'verbose_name_plural': 'Press Release Archives'},
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='archive_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='public_relations.publicrelationsarchive', verbose_name='Archive Entry'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='asset_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('drive', 'Google Drive'), ('youtube', 'YouTube'), ('facebook', 'Facebook')], max_length=10, verbose_name='Asset Type'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='caption',
            field=models.CharField(blank=True, max_length=500, verbose_name='Caption / Description'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Asset Link / File URL (e.g. Google Drive)'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='External Link (YouTube/Drive/Facebook)'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='The year this asset belongs to', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='archive_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='public_relations.publicrelationsarchive', verbose_name='Archive Entry'),
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='media_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='public_relations.mediahouse', verbose_name='Media House'),
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='newspaper_pdf',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Newspaper PDF Link (e.g. Google Drive)'),
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='online_link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Online News Link'),
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Published Date'),
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='screenshot',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Screenshot Link (e.g. Google Drive)'),
        ),
        migrations.AlterField(
            model_name='mediahouse',
            name='editor',
            field=models.CharField(blank=True, help_text='Name of the Chief Editor', max_length=255, verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='mediahouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='mediahouse',
            name='media_type',
            field=models.CharField(choices=[('national', 'National Newspaper'), ('local', 'Local Newspaper'), ('online', 'Online Portal')], max_length=10, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='mediahouse',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number (e.g. 01712345678)', regex='^(?:\\+?88)?01[3-9]\\d{8}$')], verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='mediahouse',
            name='name',
            field=models.CharField(help_text='Full name of the media house or portal', max_length=255, unique=True, verbose_name='Media Name'),
        ),
        migrations.AlterField(
            model_name='mediahouse',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='mediahouse',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number (e.g. 01712345678)', regex='^(?:\\+?88)?01[3-9]\\d{8}$')], verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_archives', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='department',
            field=models.CharField(blank=True, help_text='Associated department or program', max_length=150, verbose_name='Department / Faculty'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='event_name',
            field=models.CharField(max_length=500, verbose_name='Event Title / Headline'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='full_text',
            field=models.TextField(help_text='The complete text of the press release', verbose_name='Press Release Full Body'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='press_release_date',
            field=models.DateField(verbose_name='Press Release Date'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='press_release_no',
            field=models.CharField(help_text='Unique identifier, e.g. PRO-2024-001', max_length=50, unique=True, verbose_name='Press Release No'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='press_release_pdf',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Press Release Link (e.g. Google Drive)'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='Remarks / Notes'),
        ),
    ]
