# Generated by Django 6.0.3 on 2026-07-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0002_alter_mediaasset_options_alter_mediacoverage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediahouse',
            name='media_type',
            field=models.CharField(choices=[('national', 'National Newspaper'), ('local', 'Local Newspaper'), ('online', 'Online Portal'), ('tv', 'TV Channel')], max_length=10, verbose_name='Media Type'),
        ),
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='full_text',
            field=models.TextField(blank=True, help_text='The complete text of the press release', verbose_name='Press Release Full Body'),
        ),
    ]
