# Generated by Django 6.0.3 on 2026-07-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0004_convert_charset_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='assets/', verbose_name='Asset File Upload'),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='newspaper_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='coverage/pdfs/', verbose_name='Published News PDF File'),
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='screenshot_file',
            field=models.ImageField(blank=True, null=True, upload_to='coverage/screenshots/', verbose_name='Published News Screenshot File'),
        ),
        migrations.AddField(
            model_name='publicrelationsarchive',
            name='press_release_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pr/pdfs/', verbose_name='Press Release PDF File'),
        ),
    ]
