# Generated by Django 6.0.3 on 2026-07-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0005_mediaasset_file_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='file',
        ),
        migrations.RemoveField(
            model_name='mediacoverage',
            name='newspaper_pdf',
        ),
        migrations.RemoveField(
            model_name='mediacoverage',
            name='screenshot',
        ),
        migrations.RemoveField(
            model_name='publicrelationsarchive',
            name='press_release_pdf',
        ),
        migrations.AlterField(
            model_name='mediacoverage',
            name='screenshot_file',
            field=models.ImageField(blank=True, null=True, upload_to='coverage/screenshots/', verbose_name='Published News Screenshot'),
        ),
    ]
