# Generated by Django 5.2.7 on 2026-07-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0006_remove_link_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='press_release_no',
            field=models.CharField(blank=True, help_text='Unique identifier, e.g. PRO-2024-001', max_length=50, unique=True, verbose_name='Press Release No'),
        ),
    ]
