# Generated by Django 5.2.7 on 2026-07-17 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0007_alter_publicrelationsarchive_press_release_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='press_release_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Press Release Date'),
        ),
    ]
