# Generated by Django 5.2.7 on 2026-07-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0008_alter_publicrelationsarchive_press_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicrelationsarchive',
            name='press_release_no',
            field=models.CharField(blank=True, help_text='Unique identifier, e.g. PR/2026/07/01', max_length=50, unique=True, verbose_name='Press Release No'),
        ),
    ]
