# Generated by Django 5.2.7 on 2026-07-17 21:28

from django.db import migrations


import datetime

def insert_pr_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    MediaHouse = apps.get_model('public_relations', 'MediaHouse')
    PublicRelationsArchive = apps.get_model('public_relations', 'PublicRelationsArchive')
    MediaCoverage = apps.get_model('public_relations', 'MediaCoverage')

    admin_user = User.objects.filter(is_superuser=True).first()
    if not admin_user:
        admin_user = User.objects.first()

    # 1. Create Media Houses
    media_houses_data = [
        ('The New Nation', 'national'),
        ('দৈনিক ইত্তেফাক', 'national'),
        ('দৈনিক সকালের বাণী', 'national'),
        ('দৈনিক করতোয়া', 'local'),
        ('দৈনিক যায়যায়দিন', 'national'),
        ('NEWS24 TV', 'tv'),
        ('journalbd24.com', 'online'),
    ]

    media_houses = {}
    for name, m_type in media_houses_data:
        mh, created = MediaHouse.objects.get_or_create(
            name=name,
            defaults={'media_type': m_type}
        )
        media_houses[name] = mh

    # 2. Press Release 1 (Serial 02)
    pr1_text = (
        "সৈয়দপুরে আর্মি বিজ্ঞান ও প্রযুক্তি বিশ্ববিদ্যালয়ে (বিএইউএসটি) ইনস্টিটিউট অব ইলেকট্রিক্যাল অ্যান্ড ইলেকট্রনিক্স "
        "ইঞ্জিনিয়ারিং (আইইইই) স্টুডেন্ট ব্রাঞ্চের উদ্যোগে তিন দিনব্যাপী আন্তর্জাতিক সম্মেলন-২০২৫ সফলভাবে সম্পন্ন হয়েছে। "
        "সম্মেলনে অংশ নেন দেশের ২৫টি বিশ্ববিদ্যালয়ের গবেষক, শিক্ষাবিদ ও প্রকৌশলীগণ।"
    )
    pr1, created = PublicRelationsArchive.objects.get_or_create(
        press_release_no='PR/2025/08/02',
        defaults={
            'press_release_date': datetime.date(2025, 8, 2),
            'event_name': 'বিএইউএসটি সৈয়দপুরে অনুষ্ঠিত হলো IEEE কনফারেন্স',
            'department': 'PR Office',
            'full_text': pr1_text,
            'remarks': 'আর্কাইভের পৃষ্ঠা নং- ০৫-১২',
            'created_by': admin_user
        }
    )

    # 3. Press Release 2 (Serial 03)
    pr2_text = (
        "বাংলাদেশ আর্মি ইউনিভার্সিটি অব সায়েন্স এন্ড টেকনোলজি (বিএইউএসটি), সৈয়দপুর-এর উদ্যোগে ৩য় ও ৪থ শ্রেণীর "
        "কর্মচারীদের পেশাগত দক্ষতা উন্নয়ন এবং দাপ্তরিক আচরণ ও শৃঙ্খলা বিষয়ে সচেতনতা বৃদ্ধির লক্ষ্যে আয়োজিত দুই দিনব্যাপী "
        "প্রশিক্ষণ কর্মসূচি গত ২৩ ও ২৪ জুলাই ২০২৫ তারিখে সফলভাবে সম্পন্ন হয়েছে।\n"
        "প্রশিক্ষণ কর্মসূচির উদ্বোধনী অনুষ্ঠানে প্রধান অতিথি হিসেবে উপস্থিত থেকে দিকনির্দেশনামূলক বক্তব্য প্রদান করেন "
        "বিশ্ববিদ্যালয়ের মাননীয় উপাচার্য ব্রিগেডিয়ার জেনারেল মোহাম্মদ মোবারক হোসেন মজুমদার, পিএসসি। তিনি সকল কর্মচারীকে "
        "যথাযথভাবে দায়িত্ব পালনের আহ্বান জানান এবং প্রশিক্ষণ থেকে অর্জিত জ্ঞান কাজে লাগিয়ে প্রাতিষ্ঠানিক শৃঙ্খলা রক্ষায় "
        "গুরুত্বপূর্ণ ভূমিকা রাখার নির্দেশনা দেন।\n"
        "অনুষ্ঠানে উপাচার্য মহোদয়ের বক্তব্য শেষে ইনস্টিটিউশনাল কোয়ালিটি অ্যাসিউরেন্স সেল (আইকিউএসি)-এর পরিচালক প্রফেসর "
        "ড. ইমতিয়াজ আহমেদ চৌধুরী বক্তব্য রাখেন। এরপর বক্তব্য রাখেন বিশ্ববিদ্যালয়ের সম্মানিত রেজিস্ট্রার কর্নেল চৌধুরী সাইফ "
        "উদ্দিন কাউসার, পিবিজিএম (এলপিআর)। তিনি অংশগ্রহণকারী সকল কর্মচারীকে আন্তরিক ধন্যবাদ জানান এবং ভবিষ্যতে আরও কার্যকর "
        "প্রশিক্ষণের আশাবাদ ব্যক্ত করেন।\n"
        "অনুষ্ঠানে আরও উপস্থিত ছিলেন বিশ্ববিদ্যালয়ের সম্মানিত ট্রেজারার, পরীক্ষা নিয়ন্ত্রক, আইকিউএসি-এর অতিরিক্ত "
        "পরিচালকবৃন্দ এবং বিভিন্ন অনুষদের ডীনবৃন্দ। প্রতিদিন সকাল ৯টা থেকে ১২টা পর্যন্ত এবং বিকাল ৩টা থেকে ৬টা পর্যন্ত "
        "দুইটি ব্যাচে প্রশিক্ষণ অনুষ্ঠিত হয়। বিশ্ববিদ্যালয়ের রেজিস্ট্রার দপ্তরের উদ্যোগে এবং ইনস্টিটিউশনাল কোয়ালিটি অ্যাসিউরেন্স "
        "সেল (আইকিউএসি)-এর সহযোগিতায় এই প্রশিক্ষণ কর্মসূচি আয়োজন করা হয়।\n"
        "প্রশিক্ষণের সকল সেশন পরিচালিত হয় বিশ্ববিদ্যালয়ের ২০৮ নম্বর স্মার্ট ক্লাসরুমে, PowerPoint প্রেজেন্টেশনের মাধ্যমে। "
        "২০৬ জন কর্মচারীর মধ্যে ১৯৪ জন সক্রিয়ভাবে প্রশিক্ষণে অংশগ্রহণ করেন।\n"
        "প্রশিক্ষণে আলোচনা করা হয়-\n"
        "১. কর্মচারী হিসেবে দায়িত্ব ও कर्तव्य\n"
        "২. বিশ্ববিদ্যালয়ের সাংগঠনিক কাঠামো\n"
        "৩. অফিসের নিয়ম-কানুন, শৃঙ্খলা ও বিধিবিধান\n"
        "৪. ফাইলিং ও নথি ব্যবস্থাপনা\n"
        "৫. দাপ্তরিক আচরণবিধি ও রিপোর্টিং সিস্টেম\n"
        "প্রতিটি সেশনের শেষে প্রশ্নোত্তর পর্বের মাধ্যমে অংশগ্রহণকারীদের মতামত ও প্রশ্নের উত্তর প্রদান করা হয়। প্রশিক্ষণ "
        "শেষে অনুষ্ঠিত হয় ১০০ নম্বরের এক মূল্যায়ন পরীক্ষা, যার মাধ্যমে অংশগ্রহণকারীদের শেখার অগ্রগতি যাচাই করা হয়। "
        "প্রশিক্ষণে অংশগ্রহণকারী কর্মচারীরা একে অত্যন্ত সময়োপযোগী ও বাস্তবমুখী উদ্যোগ হিসেবে উল্লেখ করে জানান, এই প্রশিক্ষণ "
        "তাদের দায়িত্ব পালনে অধিক মনোযোগী, সচেতন এবং আত্মবিশ্বাসী হতে সহায়তা করবে।\n"
        "ধন্যবাদান্তে,\n"
        "মোঃ শাহ্ আলম\n"
        "জনসংযোগ কর্মকর্তা\n"
        "বিএইউএসটি, সৈয়দপুর"
    )
    pr2, created = PublicRelationsArchive.objects.get_or_create(
        press_release_no='PR/2025/08/03',
        defaults={
            'press_release_date': datetime.date(2025, 8, 13),
            'event_name': 'বিএইউএসটি কর্মচারীদের দুইদিনব্যাপী প্রশিক্ষণ কর্মসূচি সম্পন্ন',
            'department': 'Registrar Office',
            'full_text': pr2_text,
            'remarks': 'আর্কাইভের পৃষ্ঠা নং- ১৩-১৭',
            'created_by': admin_user
        }
    )

    # 4. Link Coverages for PR 1
    pr1_media = ['The New Nation', 'দৈনিক ইত্তেফাক', 'দৈনিক সকালের বাণী', 'দৈনিক করতোয়া', 'দৈনিক যায়যায়দিন', 'NEWS24 TV']
    for name in pr1_media:
        mh = media_houses[name]
        MediaCoverage.objects.get_or_create(
            archive_entry=pr1,
            media_house=mh,
            defaults={'published_date': datetime.date(2025, 8, 3)}
        )

    # 5. Link Coverages for PR 2
    pr2_media = ['দৈনিক সকালের বাণী', 'journalbd24.com']
    for name in pr2_media:
        mh = media_houses[name]
        MediaCoverage.objects.get_or_create(
            archive_entry=pr2,
            media_house=mh,
            defaults={'published_date': datetime.date(2025, 8, 14)}
        )

def remove_pr_data(apps, schema_editor):
    PublicRelationsArchive = apps.get_model('public_relations', 'PublicRelationsArchive')
    PublicRelationsArchive.objects.filter(press_release_no__in=['PR/2025/08/02', 'PR/2025/08/03']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0009_alter_publicrelationsarchive_press_release_no'),
    ]

    operations = [
        migrations.RunPython(insert_pr_data, reverse_code=remove_pr_data),
    ]
