# Generated by Django 5.2.7 on 2026-07-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_relations', '0010_auto_20260718_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacoverage',
            name='online_link',
            field=models.TextField(blank=True, help_text='Multiple links can be stored (one per line)', verbose_name='Online News Link(s)'),
        ),
    ]
