# Generated by Django 5.2.7 on 2026-04-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='ADMISSION SUITE', max_length=255)),
                ('institution_logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('theme_color', models.CharField(default='#1e40af', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
