# Generated by Django 6.0.3 on 2026-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='institution_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='institution_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
