# Generated by Django 5.2.7 on 2026-04-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_api_url',
            field=models.URLField(blank=True, help_text='The endpoint for the SMS gateway (e.g. BulkSMSBD, GreenWeb)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sms_sender_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
