# Generated by Django 5.2.7 on 2026-04-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='navbar_fixed',
            field=models.BooleanField(default=True),
        ),
    ]
