# Generated by Django 6.0.3 on 2026-04-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_department_userprofile_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='is_system_alert',
            field=models.BooleanField(default=False, help_text='If true, visible to all authorized staff regardless of scope'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='scope',
            field=models.CharField(blank=True, help_text='e.g. Department name for scoped notifications', max_length=100, null=True),
        ),
    ]
