# Generated by Django 6.0.3 on 2026-05-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activitylog_is_system_alert_activitylog_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='auto_id_generation',
            field=models.BooleanField(default=True, help_text='If enabled, Student IDs are generated automatically and locked. If disabled, staff can enter IDs manually.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='institution_name',
            field=models.CharField(default='Bangladesh Army University of Science and Technology', max_length=255),
        ),
    ]
