# Generated by Django 6.0.3 on 2026-05-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsettings_auto_id_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='auto_id_generation',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='id_mode',
            field=models.CharField(choices=[('auto', 'Auto — System generates full 16-digit ID automatically'), ('semi_auto', 'Semi-Auto — System generates prefix; staff enters last 3 serial digits'), ('manual', 'Manual — Staff types the complete 16-digit UGC ID')], default='semi_auto', help_text='Controls how the Student ID is generated on the admission form.', max_length=10),
        ),
    ]
