# Generated by Django 5.2.7 on 2026-07-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_id_mode_to_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Ruhulamin Siddique', max_length=255)),
                ('title', models.CharField(default='Lecturer', help_text='e.g. Lecturer, Senior Developer', max_length=150)),
                ('department', models.CharField(default='CSE', help_text='Short dept name, e.g. CSE', max_length=100)),
                ('institution', models.CharField(default='Bangladesh Army University of Science and Technology', max_length=255)),
                ('tagline', models.CharField(blank=True, help_text="Short animated typing tagline, e.g. 'Django Developer | Researcher | Educator'", max_length=255)),
                ('bio', models.TextField(blank=True, help_text='About Me paragraph shown on portfolio page')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='developer/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('github_url', models.URLField(blank=True, default='https://github.com/ruhulamin-siddique')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, help_text='Optional external personal website', null=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('is_available_for_work', models.BooleanField(default=True, help_text="Shows an 'Open to Work' badge on the hero section")),
                ('visit_count', models.PositiveIntegerField(default=0, help_text='Auto-incremented on each page view')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Developer Profile',
                'verbose_name_plural': 'Developer Profile',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-trophy', help_text='Font Awesome icon class', max_length=80)),
                ('date_earned', models.DateField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.developerprofile')),
            ],
            options={
                'ordering': ['sort_order', '-date_earned'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g. B.Sc in Computer Science & Engineering', max_length=150)),
                ('institution', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('gpa', models.CharField(blank=True, help_text='e.g. 3.75/4.00', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_set', to='core.developerprofile')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['sort_order', '-start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('research', 'Research'), ('teaching', 'Teaching'), ('internship', 'Internship')], default='fulltime', max_length=15)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='core.developerprofile')),
            ],
            options={
                'ordering': ['sort_order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(blank=True, help_text='Comma-separated: Python, Django, PostgreSQL', max_length=500)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('live', 'Live'), ('dev', 'In Development'), ('archived', 'Archived')], default='live', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='developer/projects/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.developerprofile')),
            ],
            options={
                'ordering': ['-is_featured', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Backend', 'Backend Development'), ('Frontend', 'Frontend Development'), ('Database', 'Database'), ('DevOps', 'DevOps & Cloud'), ('Tools', 'Tools & Software'), ('Soft', 'Soft Skills'), ('Research', 'Research & Academic'), ('Other', 'Other')], default='Other', max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='0–100 percentage for progress bar')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome class e.g. 'fab fa-python'", max_length=80)),
                ('sort_order', models.IntegerField(default=0)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.developerprofile')),
            ],
            options={
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
    ]
