# Generated by Django 5.2.7 on 2026-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_developer_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bangla')], default='bn', max_length=10),
        ),
    ]
