# Generated by Django 6.0.3 on 2026-07-15 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty Member'), ('officer', 'Officer'), ('staff', 'Staff Member'), ('other', 'Other')], default='student', max_length=20)),
                ('department', models.CharField(help_text='e.g. CSE, EEE, ME, CE, BBA', max_length=150)),
                ('designation_or_roll', models.CharField(help_text='Designation (for staff/faculty) or Roll/ID Number (for students)', max_length=100)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('mobile', 'Mobile / Tablet'), ('desktop', 'Desktop PC'), ('other', 'Other')], default='laptop', max_length=20)),
                ('device_name_brand', models.CharField(help_text='e.g. Asus ROG, iPhone 14, Dell Inspiron', max_length=150)),
                ('mac_address', models.CharField(help_text='Physical address of your network card (Wi-Fi/Ethernet)', max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address in format XX:XX:XX:XX:XX:XX or XX-XX-XX-XX-XX-XX', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('reason', models.TextField(blank=True, help_text='Why do you require Wi-Fi/network access?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('assigned_ip', models.GenericIPAddressField(blank=True, help_text='Assigned IP address (Admin only)', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='ICT administrator notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Registration',
                'verbose_name_plural': 'Device Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
