# Generated by Django 6.0.3 on 2026-07-15 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_wing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregistration',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number (e.g. 01712345678 or +8801712345678)', regex='^(?:\\+?88)?01[3-9]\\d{8}$')]),
        ),
    ]
