from django.urls import path

from . import views


urlpatterns = [
    path('', views.dashboard, name='billing_dashboard'),
    path('settings/rates/', views.rate_templates, name='billing_rate_templates'),
    path('exams/', views.exam_list, name='billing_exam_list'),
    path('exams/create/', views.exam_create, name='billing_exam_create'),
    path('exams/<int:pk>/', views.exam_detail, name='billing_exam_detail'),
    path('exams/<int:pk>/edit/', views.exam_edit, name='billing_exam_edit'),
    path('exams/<int:pk>/delete/', views.exam_delete, name='billing_exam_delete'),
    path('exams/<int:pk>/settings/', views.exam_settings, name='billing_exam_settings'),
    path('exams/<int:pk>/status/<str:action>/', views.exam_status, name='billing_exam_status'),
    path('faculty/export-template/', views.faculty_export_template, name='billing_faculty_export_template'),
    path('faculty/import/', views.faculty_import, name='billing_faculty_import'),
    path('faculty/', views.faculty_directory, name='billing_faculty_directory'),
    path('faculty/<int:pk>/edit/', views.faculty_edit, name='billing_faculty_edit'),
    path('faculty/<int:pk>/delete/', views.faculty_delete, name='billing_faculty_delete'),
    path('programs/<int:pk>/', views.program_workspace, name='billing_program_workspace'),
    path('programs/<int:pk>/copy-faculty/', views.copy_faculty_to_exam, name='billing_copy_faculty'),
    path('programs/<int:pk>/copy-previous/', views.copy_previous_program_data, name='billing_copy_previous'),
    path('programs/<int:pk>/submit/', views.program_submit, name='billing_program_submit'),
    path('programs/<int:pk>/status/<str:action>/', views.program_status, name='billing_program_status'),
    path('programs/<int:pk>/summary.csv', views.summary_csv, name='billing_summary_csv'),
    path('programs/<int:pk>/print-package/', views.printable_package, name='billing_printable_package'),
    path('programs/<int:pk>/fundamentals/', views.program_fundamentals, name='billing_program_fundamentals'),
    path('programs/<int:pk>/fundamentals/course/<int:course_id>/edit/', views.program_course_edit, name='billing_course_edit'),
    path('programs/<int:pk>/fundamentals/summary/<int:summary_id>/edit/', views.program_summary_edit, name='billing_summary_edit'),
    path('programs/<int:pk>/fundamentals/summary/<int:summary_id>/delete/', views.program_summary_delete, name='billing_summary_delete'),
    path('programs/<int:pk>/workspace/', views.program_workspace, name='billing_program_workspace_alt'),
    path('programs/<int:pk>/faculty/<int:faculty_id>/remove/', views.program_faculty_remove, name='billing_program_faculty_remove'),
    path('programs/<int:pk>/sheets/<str:sheet>/', views.program_sheet, name='billing_program_sheet'),
    path('programs/<int:pk>/sheets/<str:sheet>/excel/', views.export_sheet_excel, name='billing_sheet_excel'),
    path('programs/<int:pk>/sheets/<str:sheet>/<int:row_id>/edit/', views.program_row_edit, name='billing_row_edit'),
    path('programs/<int:pk>/sheets/<str:sheet>/<int:row_id>/delete/', views.program_sheet_delete, name='billing_program_sheet_delete'),
    path('programs/<int:pk>/sheets/<str:sheet>/<int:row_id>/delete-confirm/', views.billing_row_delete_confirm, name='billing_row_delete_confirm'),
    path('ajax/course-info/', views.get_course_info, name='billing_get_course_info'),
    path('ajax/check-course-assignments/', views.check_course_assignments, name='billing_check_course_assignments'),
    path('programs/<int:pk>/individual/<int:faculty_id>/', views.individual_bill, name='billing_individual_bill'),
    path('programs/<int:pk>/individual/<int:faculty_id>/excel/', views.faculty_bill_excel, name='billing_faculty_bill_excel'),
    path('fundamentals/', views.fundamentals_hub, name='billing_fundamentals_hub'),
    path('individual-bills/', views.individual_bills_directory, name='billing_individual_bills_directory'),
]
