# Generated by Django 6.0.3 on 2026-04-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='UGC Cluster Code (e.g., 05)', max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Clusters',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Internal/UGC Hall Code (e.g., 01)', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(help_text='Semester code (1 or 2)', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ugc_code', models.CharField(help_text='UGC Subject Code (e.g., 01 for CSE)', max_length=10, unique=True)),
                ('level_code', models.CharField(choices=[('1', 'Bachelor'), ('3', 'Masters')], default='1', max_length=1)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='master_data.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admission_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.admissionyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='master_data.program')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'unique_together': {('name', 'program', 'admission_year')},
            },
        ),
    ]
