# Generated by Django 6.0.3 on 2026-04-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-sort_order', 'name'], 'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='batch',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first'),
        ),
    ]
