# Generated by Django 5.2.7 on 2026-04-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_batch_options_batch_sort_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'admission_year')},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='program',
        ),
    ]
