# Generated by Django 5.2.7 on 2026-04-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_alter_batch_unique_together_remove_batch_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='program',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short Name (e.g., CSE)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='program',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Higher numbers appear first'),
        ),
        migrations.AlterField(
            model_name='program',
            name='level_code',
            field=models.CharField(choices=[('1', 'Bachelor'), ('3', 'Masters')], default='1', max_length=1, verbose_name='Program Type'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Full Name (e.g., Computer Science and Engineering)', max_length=150, unique=True),
        ),
    ]
