# Generated by Django 5.2.7 on 2026-04-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_alter_program_options_program_short_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='name',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='hall',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
