# Generated by Django 5.2.7 on 2026-04-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_rename_name_hall_short_name_hall_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='is_engineering',
            field=models.BooleanField(default=True),
        ),
    ]
