# Generated by Django 6.0.3 on 2026-05-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_cluster_is_engineering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='ugc_code',
            field=models.CharField(help_text='UGC Subject Code (e.g., 01 for CSE)', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('cluster', 'ugc_code', 'level_code')},
        ),
    ]
