# Generated by Django 5.2.7 on 2026-07-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_set_english_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='code',
            field=models.CharField(help_text='Internal/UGC Hall Code (e.g., 01)', max_length=10),
        ),
    ]
