# Generated by Django 5.2.7 on 2026-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_alter_hall_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total physical seat capacity of the hall'),
        ),
    ]
